export const TeamMembers = {
    "Executive Board" : [
        {
            group: "Executive Board",
            name : "john",
            position : "fella",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
            linkedin: "https://www.linkedin.com/in/w-hager/",

        },
        {
            group: "Executive Board",
            name : "joan",
            position : "gal",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group: "Executive Board",
            name : "freddy",
            position : "director of balling",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group: "Executive Board",
            name : "zofka",
            position : "ceo of just chillin",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group: "Executive Board",
            name : "leopold",
            position : "steering wheel designer",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },

    ],
    "Subsystem Leads" : [
        {
            group : "Subsystem Leads",
            name : "john",
            position : "fella",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Subsystem Leads",
            name : "joan",
            position : "gal",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Subsystem Leads",
            name : "freddy",
            position : "director of balling",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Subsystem Leads",
            name : "zofka",
            position : "ceo of just chillin",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Subsystem Leads",
            name : "leopold",
            position : "steering wheel designer",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        }
    ],
    "Project Team Leads" : [
        {
            group : "Project Team Leads",
            name : "john",
            position : "fella",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Project Team Leads",
            name : "joan",
            position : "gal",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Project Team Leads",
            name : "freddy",
            position : "director of balling",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Project Team Leads",
            name : "zofka",
            position : "ceo of just chillin",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        },
        {
            group : "Project Team Leads",
            name : "leopold",
            position : "steering wheel designer",
            img: "/team_member_pics/profile-pic-default.png",
            role: "Transmission",
            major: "Mechanical Engineering",
            year: "3rd",
        }
    ]
}